/**
 * Accessibility instrumentation for generated Playwright tests.
 *
 * Every spec the platform runs imports `test` from `@playwright/test`. At run
 * time the runners rewrite that import to a workspace-local fixture (written
 * from `a11yFixtureSource()`) that re-exports Playwright unchanged and adds an
 * automatic fixture which runs axe-core:
 *
 *   - after every `page.goto()`            → the page as first rendered
 *   - after every `test.step()`            → the state the step left behind
 *   - at the end of the test               → the final state
 *
 * Checkpoints whose DOM has not changed since the previous scan are skipped,
 * so a test with five steps on one static page produces one scan, not five.
 * Results are attached to the test (visible in the Playwright HTML and Allure
 * reports) and written as JSON to `JBS_A11Y_DIR`, where the runner collects
 * them into an `A11ySummary`. Violations never fail a test — they are
 * reported, not gated, so a green run still tells the truth about WCAG.
 */
import fs from 'fs/promises';
import path from 'path';

export const A11Y_FIXTURE_BASENAME = 'a11y.fixture.ts';
export const A11Y_RESULTS_DIRNAME = 'a11y-results';

/** One axe run at one point in one test. */
export interface A11yCheckpoint {
  testFile: string;
  testTitle: string;
  checkpoint: string;
  url: string;
  at: string;
  violations: A11yViolation[];
  passes: number;
  incomplete: number;
}

export interface A11yViolation {
  id: string;
  impact: 'critical' | 'serious' | 'moderate' | 'minor' | null;
  help: string;
  description: string;
  helpUrl: string;
  tags: string[];
  /** Every failing node counts; only the first few are kept. */
  nodeCount: number;
  nodes: { target: string[]; html: string; failureSummary?: string }[];
}

export interface A11ySummary {
  /** Axe runs performed (after goto / after step / end of test), deduplicated by DOM state. */
  checkpoints: number;
  /** Distinct URLs scanned. */
  pagesScanned: number;
  /** Tests that produced at least one checkpoint. */
  testsScanned: number;
  /** Total failing nodes across all checkpoints. */
  violations: number;
  byImpact: Record<'critical' | 'serious' | 'moderate' | 'minor', number>;
  /** Failing rules, worst first. */
  rules: { id: string; help: string; helpUrl: string; impact: A11yViolation['impact']; wcag: string[]; nodes: number; checkpoints: number; pages: string[] }[];
  /** Per-checkpoint detail, kept for the report. */
  details: A11yCheckpoint[];
}

/**
 * Source of the fixture module. Plain TypeScript: Playwright transpiles it
 * and `@axe-core/playwright` resolves through NODE_PATH (backend/node_modules)
 * exactly like the specs' own imports.
 */
export function a11yFixtureSource(): string {
  return `// Generated by IntelliQE — accessibility checkpoints for every test. Do not edit.
import { test as base } from '@playwright/test';
import type { Page, TestInfo } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import * as fs from 'fs';
import * as path from 'path';

export * from '@playwright/test';

const OUT_DIR = process.env.JBS_A11Y_DIR || '';
const TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa'];
const MAX_NODES = 10;

interface Current { page: Page; info: TestInfo; seen: Set<string>; n: number }
let current: Current | null = null;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'checkpoint';

/** Run axe on the current page state unless this exact state was already scanned in this test. */
async function scan(label: string): Promise<void> {
  const c = current;
  if (!c) return;
  let url = '';
  try { url = c.page.url(); } catch { return; }
  if (!url || url === 'about:blank') return;
  let signature = '';
  try {
    signature = await c.page.evaluate(() => location.href + '|' + (document.body ? document.body.innerHTML.length : 0));
  } catch { return; } // navigating away — nothing stable to scan
  if (c.seen.has(signature)) return;
  c.seen.add(signature);

  let results: Awaited<ReturnType<AxeBuilder['analyze']>>;
  try {
    results = await new AxeBuilder({ page: c.page }).withTags(TAGS).analyze();
  } catch { return; } // page closed or context destroyed mid-scan
  c.n += 1;
  const violations = results.violations.map((v) => ({
    id: v.id, impact: (v.impact as string | undefined) || null, help: v.help, description: v.description, helpUrl: v.helpUrl, tags: v.tags,
    nodeCount: v.nodes.length,
    nodes: v.nodes.slice(0, MAX_NODES).map((n) => ({ target: (n.target || []).map(String), html: (n.html || '').slice(0, 500), failureSummary: n.failureSummary })),
  }));
  const record = {
    testFile: path.basename(c.info.file), testTitle: c.info.title, checkpoint: label, url, at: new Date().toISOString(),
    violations, passes: results.passes.length, incomplete: results.incomplete.length,
  };
  const total = violations.reduce((a, v) => a + v.nodeCount, 0);
  c.info.annotations.push({ type: 'accessibility', description: label + ': ' + total + ' WCAG violation' + (total === 1 ? '' : 's') + ' on ' + url });
  await c.info.attach('accessibility-' + c.n + '-' + slug(label) + '.json', { body: JSON.stringify(record, null, 2), contentType: 'application/json' }).catch(() => {});
  if (OUT_DIR) {
    try {
      fs.mkdirSync(OUT_DIR, { recursive: true });
      fs.writeFileSync(path.join(OUT_DIR, c.info.workerIndex + '-' + Date.now() + '-' + c.n + '.json'), JSON.stringify(record));
    } catch { /* results dir not writable — the attachment above still carries the data */ }
  }
}

export const test = base.extend<{ a11y: void }>({
  a11y: [async ({ page }, use, testInfo) => {
    current = { page, info: testInfo, seen: new Set(), n: 0 };
    const origGoto = page.goto.bind(page);
    page.goto = (async (url: string, options?: Parameters<Page['goto']>[1]) => {
      const response = await origGoto(url, options);
      await scan('after goto ' + url);
      return response;
    }) as Page['goto'];
    await use();
    await scan('end of test');
    current = null;
  }, { auto: true }],
});

// A checkpoint after every step, so states reached by clicking, typing and
// submitting are scanned — not just the page as it first loaded.
const origStep = test.step;
(test as unknown as { step: unknown }).step = async function <T>(title: string, body: () => Promise<T> | T, options?: { box?: boolean }): Promise<T> {
  const result = await (origStep as (t: string, b: () => Promise<T> | T, o?: { box?: boolean }) => Promise<T>).call(test, title, body, options);
  await scan('after step: ' + title);
  return result;
};
`;
}

/**
 * Point a spec's Playwright import at the fixture. Page objects are left
 * alone — they only import types from '@playwright/test'.
 */
export function rewritePlaywrightImports(code: string, fixtureImportPath: string): string {
  return code.replace(/(['"])@playwright\/test\1/g, `'${fixtureImportPath}'`);
}

/** Relative import path (posix, no extension) from a spec file to the fixture at the workspace root. */
export function fixtureImportPathFor(workspace: string, specAbsPath: string): string {
  const rel = path.relative(path.dirname(specAbsPath), path.join(workspace, A11Y_FIXTURE_BASENAME)).replace(/\\/g, '/').replace(/\.ts$/, '');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

export async function writeA11yFixture(workspace: string): Promise<void> {
  await fs.writeFile(path.join(workspace, A11Y_FIXTURE_BASENAME), a11yFixtureSource(), 'utf-8');
}

export async function collectA11yResults(dir: string): Promise<A11yCheckpoint[]> {
  const files = await fs.readdir(dir).catch(() => [] as string[]);
  const out: A11yCheckpoint[] = [];
  for (const f of files) {
    if (!f.endsWith('.json')) continue;
    try { out.push(JSON.parse(await fs.readFile(path.join(dir, f), 'utf-8'))); } catch { /* partial write — skip */ }
  }
  return out.sort((a, b) => a.at.localeCompare(b.at));
}

const IMPACT_ORDER = { critical: 0, serious: 1, moderate: 2, minor: 3 } as const;

export function summariseA11y(checkpoints: A11yCheckpoint[]): A11ySummary {
  const byImpact = { critical: 0, serious: 0, moderate: 0, minor: 0 };
  const rules = new Map<string, A11ySummary['rules'][number] & { pageSet: Set<string> }>();
  let violations = 0;
  for (const c of checkpoints) {
    for (const v of c.violations) {
      violations += v.nodeCount;
      byImpact[v.impact || 'minor'] += v.nodeCount;
      const r = rules.get(v.id) || { id: v.id, help: v.help, helpUrl: v.helpUrl, impact: v.impact, wcag: v.tags.filter((t) => /^wcag\d/.test(t)), nodes: 0, checkpoints: 0, pages: [], pageSet: new Set<string>() };
      r.nodes += v.nodeCount;
      r.checkpoints += 1;
      r.pageSet.add(c.url);
      rules.set(v.id, r);
    }
  }
  return {
    checkpoints: checkpoints.length,
    pagesScanned: new Set(checkpoints.map((c) => c.url)).size,
    testsScanned: new Set(checkpoints.map((c) => `${c.testFile}::${c.testTitle}`)).size,
    violations,
    byImpact,
    rules: [...rules.values()]
      .sort((a, b) => IMPACT_ORDER[a.impact || 'minor'] - IMPACT_ORDER[b.impact || 'minor'] || b.nodes - a.nodes)
      .map(({ pageSet, ...r }) => ({ ...r, pages: [...pageSet] })),
    details: checkpoints,
  };
}
