/**
 * client-package.templates.ts
 * ───────────────────────────
 * The STATIC part of the IP-safe client deliverable, emitted as string
 * constants. These are the environment-agnostic runner files (config,
 * package.json, base page object, common utilities, CI workflow, folder
 * placeholders) that ship UNCHANGED with every published suite.
 *
 * Why constants and not an on-disk template dir: like the existing
 * `CI_WORKFLOW_CONTENT` in client-deliverable.service.ts, embedding the
 * scaffold in the compiled backend makes publishing deployment-robust — no
 * runtime filesystem lookup, no Dockerfile copy, no extra env var. The
 * execution scaffold under `client-deliverable/src` is left solely for the
 * pipeline's ephemeral execution workspace and is NOT reused here.
 *
 * LAYOUT (top-level, no `src/` wrapper):
 *   pages/            page objects (base.page.ts + generated <module>/<name>.page.ts)
 *   common/           env, test-data loader, fixtures, matchers, logger, types
 *   data/testdata/    non-sensitive JSON fixtures
 *   specs/            Markdown test plan (basic-operations.md, generated)
 *   tests/            one spec per module: <module>/<module>.spec.ts (generated)
 *   report/ traces/ logs/   runtime output (report, traces+videos, logs)
 *   .github/workflows/      CI (GitHub Actions)
 */
import type { GitFile } from './git/git.types.js';

/** Path of the CI/CD workflow in the delivered repo. */
export const DELIVERY_CI_WORKFLOW_PATH = '.github/workflows/playwright.yml';

/* ─────────────────────────── runner config ─────────────────────────── */

const PLAYWRIGHT_CONFIG = `import { defineConfig, devices } from '@playwright/test';
import { env } from './common/env';

/**
 * Playwright configuration — environment-agnostic, Page Object Model.
 *
 * Chromium by default. Runs fully in parallel. Saves a video AND a trace for
 * EVERY test (not just failures) so every run is fully reproducible. All
 * behavior is driven by variables in .env (see .env.example).
 */
export default defineConfig({
  testDir: './tests',
  // Closes the shared DB pool (if a test opened one) after the run so the
  // Node process exits cleanly. Safe no-op when no test touched the database.
  globalTeardown: './common/global-teardown.ts',
  // Traces, videos and screenshots for every test land here.
  outputDir: './traces',
  fullyParallel: true,
  forbidOnly: env.CI,
  retries: env.CI ? 2 : 0,
  workers: env.WORKERS,
  timeout: env.TIMEOUT,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: './report/html' }],
    ['junit', { outputFile: './report/junit.xml' }],
    ['json', { outputFile: './logs/test-results.json' }],
  ],
  use: {
    baseURL: env.BASE_URL,
    headless: env.HEADLESS,
    // Always-on: capture a trace and a video for every test execution.
    trace: 'on',
    video: 'on',
    screenshot: 'only-on-failure',
  },
  // Chromium is the default browser. Add firefox/webkit projects here if needed.
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
`;

const PACKAGE_JSON = `{
  "name": "qe-playwright-tests",
  "version": "1.0.0",
  "private": true,
  "description": "Playwright end-to-end test suite (Page Object Model). Generated by JBS IntelliQE.",
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "test:ui": "playwright test --ui",
    "test:chromium": "playwright test --project=chromium",
    "report": "playwright show-report ./report/html",
    "install:browsers": "playwright install chromium"
  },
  "devDependencies": {
    "@playwright/test": "^1.58.2",
    "@types/mssql": "^9.1.5",
    "@types/node": "^20.11.0",
    "mssql": "^10.0.2",
    "typescript": "^5.4.0"
  }
}
`;

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "CommonJS",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "strict": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "types": ["node"]
  },
  "include": ["pages", "common", "tests", "playwright.config.ts"],
  "exclude": ["node_modules", "report", "traces", "logs", "test-results"]
}
`;

const ENV_EXAMPLE = `# --- Required ---
# Base URL of the application under test.
# In GitHub Actions this comes from the BASE_URL repository secret.
BASE_URL=https://app.example.com

# --- Credentials ---
# Used by tests that sign in. In CI these come from GitHub Actions secrets
# (Settings -> Secrets and variables -> Actions): APP_USERNAME, APP_PASSWORD.
APP_USERNAME=
APP_PASSWORD=

# --- Database validation (optional) ---
# Tests can assert on the application's Azure SQL database via common/db.ts.
# In CI these values come from GitHub Actions secrets. Leave blank if your tests
# do not touch the database.
# Provide discrete fields...
DB_SERVER=your-server.database.windows.net
DB_DATABASE=your-database
DB_USER=your-username
DB_PASSWORD=
DB_PORT=1433
# Encryption is ON by default (required by Azure SQL); set false only for local.
DB_ENCRYPT=true
DB_TRUST_SERVER_CERT=false
# ...or a single connection string, which takes precedence over the fields above.
# DB_CONNECTION_STRING=

# --- Optional (safe defaults) ---
# Run browsers headless (true/false).
HEADLESS=true
# Parallel worker count.
WORKERS=4
# Per-test timeout in milliseconds.
TIMEOUT=30000
# Set to true in CI to enable retries and forbid .only.
CI=false
`;

const GITIGNORE = `node_modules
test-results
.env
.DS_Store

# Keep the output folders in the repo, ignore their runtime contents.
report/*
!report/.gitkeep
traces/*
!traces/.gitkeep
logs/*
!logs/.gitkeep
`;

// NOTE: \${{ ... }} below is escaped so the emitted YAML keeps the GitHub
// Actions expression syntax verbatim.
const WORKFLOW = `name: Playwright Tests

# CI/CD for the IntelliQE-generated Playwright suite.
# Runs on every push / pull request to the main branch, and on demand.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright tests (chromium)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # No lockfile is shipped, so fall back to npm install.
      - name: Install dependencies
        run: npm ci || npm install

      - name: Install Playwright browser (chromium)
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test
        env:
          # Provide these under Settings -> Secrets and variables -> Actions.
          BASE_URL: \${{ secrets.BASE_URL }}
          APP_USERNAME: \${{ secrets.APP_USERNAME }}
          APP_PASSWORD: \${{ secrets.APP_PASSWORD }}
          # Azure SQL DB validation (optional) — set these secrets if tests query the DB.
          DB_SERVER: \${{ secrets.DB_SERVER }}
          DB_DATABASE: \${{ secrets.DB_DATABASE }}
          DB_USER: \${{ secrets.DB_USER }}
          DB_PASSWORD: \${{ secrets.DB_PASSWORD }}
          DB_CONNECTION_STRING: \${{ secrets.DB_CONNECTION_STRING }}
          HEADLESS: 'true'
          CI: 'true'

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: playwright-report
          path: report/
          retention-days: 30

      - name: Upload traces and videos
        uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: traces
          path: traces/
          retention-days: 30

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: logs
          path: logs/
          retention-days: 30
`;

const README = `# QE Playwright Tests — Page Object Model

Human-readable Playwright test suite in a Page Object Model layout. Generated by
JBS IntelliQE. Environment-agnostic, no hardcoded credentials, chromium by
default, runs in parallel, and saves a video + trace for every test.

## Prerequisites

- Node.js 18 or newer

## Install

    npm ci
    npm run install:browsers
    cp .env.example .env
    # then edit .env: set BASE_URL (and APP_USERNAME / APP_PASSWORD if tests sign in)

## Run

    npm test              # headless, chromium
    npm run test:headed   # headed
    npm run test:ui       # interactive UI mode
    npm run report        # open the last HTML report

## Layout

    playwright.config.ts   Playwright config (testDir ./tests, chromium, parallel)
    package.json  tsconfig.json  .env.example
    pages/                 page objects
      base.page.ts         BasePage that every page object extends
      <module>/            e.g. auth/login.page.ts
      components/          shared components
    common/                env, db (Azure SQL), test-data loader, fixtures, matchers, logger
    data/testdata/         JSON test data (non-sensitive)
    specs/                 Markdown test plan (basic-operations.md)
    tests/                 one spec per module: <module>/<module>.spec.ts
    report/                HTML + JUnit report output
    traces/                Playwright traces and videos
    logs/                  execution logs
    .github/workflows/     CI (GitHub Actions)

Specs talk to page objects, never to raw selectors. When the UI changes, fix the
page object under pages/, not the tests.

## Configuration

All behavior is driven by .env (see .env.example). No code edits are required to
change target environment, parallelism, or browser mode. In CI, BASE_URL,
APP_USERNAME and APP_PASSWORD come from GitHub Actions secrets.

## Database validation (optional)

Tests can assert on the application's Azure SQL database through common/db.ts.
Set the DB_* values in .env (from GitHub Actions secrets in CI), then query from
a spec or page object:

    import { db } from '../../common/db';

    const row = await db.queryOne('SELECT id FROM Orders WHERE ref = @ref', { ref });
    expect(row).not.toBeNull();

The connection pool is shared across the run and closed automatically in global
teardown. The code is unchanged per customer — just point the DB_* secrets at
that customer's Azure SQL database. In CI, allow the runner's IP through the
Azure SQL firewall.
`;

/* ─────────────────────────── pages/ ─────────────────────────── */

const BASE_PAGE = `import { Page, Locator, expect } from '@playwright/test';

/**
 * BasePage — the contract every page object extends.
 *
 * Page objects encapsulate the selectors and interactions for one page (or a
 * cohesive area of one). Specs talk to page objects, never to raw selectors —
 * that is the whole point of the Page Object Model: when the UI changes, you fix
 * one page object, not dozens of tests.
 */
export abstract class BasePage {
  constructor(protected readonly page: Page) {}

  /** Navigate to a path relative to the configured baseURL (or a full URL). */
  async goto(path = '/'): Promise<void> {
    await this.page.goto(path);
  }

  /** Wait until a locator is visible (auto-waiting; no fixed sleeps). */
  async waitForVisible(locator: Locator, timeout = 15000): Promise<void> {
    await expect(locator).toBeVisible({ timeout });
  }

  /** Current page title. */
  async title(): Promise<string> {
    return this.page.title();
  }
}
`;

/* ─────────────────────────── common/ ─────────────────────────── */

const COMMON_ENV = `/**
 * Environment configuration.
 * Reads from process.env with safe defaults. No secrets, no hardcoded URLs.
 * Override any value by setting it in .env (see .env.example).
 */

function bool(v: string | undefined, fallback: boolean): boolean {
  if (v === undefined) return fallback;
  return /^(1|true|yes|on)$/i.test(v);
}

function int(v: string | undefined, fallback: number): number {
  const n = Number(v);
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

export const env = {
  BASE_URL: process.env.BASE_URL ?? 'http://localhost:3000',
  APP_USERNAME: process.env.APP_USERNAME ?? '',
  APP_PASSWORD: process.env.APP_PASSWORD ?? '',
  HEADLESS: bool(process.env.HEADLESS, true),
  WORKERS: int(process.env.WORKERS, 4),
  TIMEOUT: int(process.env.TIMEOUT, 30000),
  CI: bool(process.env.CI, false),
};

export type Env = typeof env;
`;

const COMMON_TEST_DATA = `/**
 * Minimal test-data loader.
 * Reads a JSON file from data/testdata/<name>.json.
 * Keep all test data in data/testdata/ — never hardcode sensitive values.
 */
import * as fs from 'fs';
import * as path from 'path';

const DATA_DIR = path.resolve(__dirname, '..', 'data', 'testdata');

export function loadData<T = unknown>(name: string): T {
  const file = path.join(DATA_DIR, name + '.json');
  if (!fs.existsSync(file)) {
    throw new Error('Test data file not found: ' + file);
  }
  return JSON.parse(fs.readFileSync(file, 'utf8')) as T;
}
`;

const COMMON_FIXTURE = `/**
 * Playwright test fixtures.
 *
 * A thin re-export so specs share a single import for test and expect. Specs
 * instantiate page objects directly, e.g. const login = new LoginPage(page).
 *
 * To inject ready-made page objects later, extend the base test here with
 * page-object fixtures.
 */
export { test, expect } from '@playwright/test';
`;

const COMMON_MATCHERS = `/**
 * Custom expect matchers.
 *
 * Placeholder for project-specific assertions. Register them by calling
 * expect.extend({ ... }) and importing this file once from a fixture so the
 * matchers load. Empty by default — no custom matchers are required to run.
 */
export {};
`;

const COMMON_TYPES = `/**
 * Shared types for the test suite.
 *
 * Add domain types here (e.g. a User, Credentials, or fixture shapes) and
 * import them from page objects, data files, or specs.
 */

/** A simple credential pair commonly used by auth page objects. */
export interface Credentials {
  username: string;
  password: string;
}
`;

// Uses string concatenation (no template literals) so this constant stays free
// of nested backticks / escapes.
const COMMON_LOGGER = `/**
 * Minimal file logger.
 * Appends newline-delimited log lines to logs/<name>.log at the package root,
 * so per-run logs ship as CI artifacts alongside Playwright traces and videos.
 */
import * as fs from 'fs';
import * as path from 'path';

const LOG_DIR = path.resolve(__dirname, '..', 'logs');

function ensureDir(): void {
  if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
}

export function log(message: string, name = 'test-run'): void {
  ensureDir();
  const line = '[' + new Date().toISOString() + '] ' + message + '\\n';
  fs.appendFileSync(path.join(LOG_DIR, name + '.log'), line);
}

export const logger = { log };
`;

// Reusable, config-driven Azure SQL helper for DB validation. No framework
// internals — every connection detail comes from env (GitHub Actions secrets in
// CI), so the same code links to any customer's Azure SQL database.
const COMMON_DB = `/**
 * Reusable Azure SQL / SQL Server connection helper for database validation.
 *
 * Configuration comes ENTIRELY from environment variables (see .env.example);
 * in CI these are provided by GitHub Actions secrets. Nothing is hardcoded, so
 * the same code links to any customer's Azure SQL database by pointing the
 * secrets at it. Use it from a spec or page object to assert on DB state:
 *
 *   import { db } from '../../common/db';
 *   const row = await db.queryOne('SELECT id FROM Orders WHERE ref = @ref', { ref });
 *   expect(row).not.toBeNull();
 */
import sql from 'mssql';

let poolPromise: Promise<sql.ConnectionPool> | null = null;

function buildConfig(): sql.config {
  const connectionString = process.env.DB_CONNECTION_STRING;
  if (connectionString) {
    // A full connection string takes precedence over discrete fields.
    return { connectionString } as unknown as sql.config;
  }
  const port = Number(process.env.DB_PORT || 1433);
  const encryptOff = /^(0|false|no|off)$/i.test(process.env.DB_ENCRYPT || '');
  return {
    server: process.env.DB_SERVER || 'localhost',
    database: process.env.DB_DATABASE || '',
    user: process.env.DB_USER || '',
    password: process.env.DB_PASSWORD || '',
    port: Number.isFinite(port) && port > 0 ? port : 1433,
    options: {
      // Azure SQL requires encryption; disable only for a local dev server.
      encrypt: !encryptOff,
      trustServerCertificate: /^(1|true|yes|on)$/i.test(process.env.DB_TRUST_SERVER_CERT || ''),
    },
    pool: { max: 5, min: 0, idleTimeoutMillis: 30000 },
  };
}

/** Lazily create and reuse a single connection pool for the whole run. */
export async function getPool(): Promise<sql.ConnectionPool> {
  if (!poolPromise) {
    poolPromise = new sql.ConnectionPool(buildConfig()).connect().catch((err) => {
      poolPromise = null; // let a later call retry after a failed connect
      throw err;
    });
  }
  return poolPromise;
}

/** Run a parameterized query and return all rows. Params bind as @key. */
export async function query<T = any>(text: string, params: Record<string, unknown> = {}): Promise<T[]> {
  const pool = await getPool();
  const request = pool.request();
  for (const [key, value] of Object.entries(params)) request.input(key, value as any);
  const result = await request.query<T>(text);
  return result.recordset as T[];
}

/** Run a query and return the first row, or null when there are none. */
export async function queryOne<T = any>(text: string, params: Record<string, unknown> = {}): Promise<T | null> {
  const rows = await query<T>(text, params);
  return rows.length > 0 ? (rows[0] as T) : null;
}

/** True when the query returns at least one row — handy for existence asserts. */
export async function exists(text: string, params: Record<string, unknown> = {}): Promise<boolean> {
  const rows = await query(text, params);
  return rows.length > 0;
}

/** Close the pool (called from global teardown so the process exits cleanly). */
export async function closePool(): Promise<void> {
  if (!poolPromise) return;
  const pool = await poolPromise.catch(() => null);
  poolPromise = null;
  if (pool) await pool.close();
}

export const db = { getPool, query, queryOne, exists, closePool };
`;

const COMMON_GLOBAL_TEARDOWN = `/**
 * Playwright global teardown. Closes the shared DB connection pool (if a test
 * opened one) so the Node process exits cleanly. No-op when the database was
 * never used.
 */
import { closePool } from './db';

export default async function globalTeardown(): Promise<void> {
  await closePool();
}
`;

/* ─────────────────────────── data/testdata ─────────────────────────── */

const SAMPLE_DATA = `{
  "exampleUser": {
    "email": "test.user@example.com",
    "displayName": "Test User"
  },
  "note": "Replace this placeholder with your own non-sensitive test data files."
}
`;

/** Non-empty placeholder so providers that skip empty blobs still keep the dir. */
const GITKEEP = '# Keep this directory.\n';

/**
 * The full static delivery scaffold as GitFile[] (repo-relative paths).
 * Generated page objects, consolidated specs, the test plan and docs are
 * overlaid on top of this by client-package.service.ts.
 */
export function deliveryScaffoldFiles(): GitFile[] {
  return [
    { path: 'playwright.config.ts', content: PLAYWRIGHT_CONFIG },
    { path: 'package.json', content: PACKAGE_JSON },
    { path: 'tsconfig.json', content: TSCONFIG },
    { path: '.env.example', content: ENV_EXAMPLE },
    { path: '.gitignore', content: GITIGNORE },
    { path: DELIVERY_CI_WORKFLOW_PATH, content: WORKFLOW },
    { path: 'README.md', content: README },
    { path: 'pages/base.page.ts', content: BASE_PAGE },
    { path: 'pages/components/.gitkeep', content: GITKEEP },
    { path: 'common/env.ts', content: COMMON_ENV },
    { path: 'common/db.ts', content: COMMON_DB },
    { path: 'common/global-teardown.ts', content: COMMON_GLOBAL_TEARDOWN },
    { path: 'common/test-data.ts', content: COMMON_TEST_DATA },
    { path: 'common/pages.fixture.ts', content: COMMON_FIXTURE },
    { path: 'common/matchers.ts', content: COMMON_MATCHERS },
    { path: 'common/types.ts', content: COMMON_TYPES },
    { path: 'common/logger.ts', content: COMMON_LOGGER },
    { path: 'data/testdata/sample.json', content: SAMPLE_DATA },
    { path: 'specs/.gitkeep', content: GITKEEP },
    { path: 'logs/.gitkeep', content: GITKEEP },
    { path: 'traces/.gitkeep', content: GITKEEP },
    { path: 'report/.gitkeep', content: GITKEEP },
  ];
}
