/**
 * test-case-doc.service.ts
 * ────────────────────────
 * Renders the generated test cases into human-readable documents that ship
 * INSIDE the client deliverable (alongside the POM specs):
 *   - docs/TEST-CASES.md  — IEEE-829-style catalog grouped by module
 *   - docs/test-cases.csv — Excel/Jira/TestRail-importable flat list
 *
 * Accepts the loosely-typed test cases the chat wizard sends back (camelCase
 * fields, optional structured `testSteps`), so it tolerates whatever shape the
 * client forwards.
 */
import type { GitFile } from './git/git.types.js';

interface AnyTestCase {
  id?: string;
  module?: string;
  submodule?: string;
  feature?: string;
  title?: string;
  scenario?: string;
  description?: string;
  precondition?: string;
  steps?: string[];
  testSteps?: { step?: number; action?: string; expected?: string; testData?: string }[];
  expectedResult?: string;
  expected?: string;
  priority?: string;
  type?: string;
  severity?: string;
  tags?: string[];
  status?: string;
}

function csvEscape(v: unknown): string {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Steps as a readable multi-line block (prefers structured testSteps). */
function stepsBlock(tc: AnyTestCase, joiner = '\n'): string {
  if (Array.isArray(tc.testSteps) && tc.testSteps.length) {
    return tc.testSteps
      .map((s, i) => {
        const n = s.step ?? i + 1;
        const exp = s.expected ? ` → Expected: ${s.expected}` : '';
        const data = s.testData ? ` [data: ${s.testData}]` : '';
        return `${n}. ${s.action || ''}${data}${exp}`;
      })
      .join(joiner);
  }
  return (tc.steps || []).map((s, i) => `${i + 1}. ${s}`).join(joiner);
}

function expectedOf(tc: AnyTestCase): string {
  return tc.expectedResult || tc.expected || '';
}

function titleOf(tc: AnyTestCase): string {
  return tc.title || tc.scenario || 'Test case';
}

/** Build the Markdown catalog, grouped by module (fallback: feature). */
function buildMarkdown(cases: AnyTestCase[]): string {
  const groups = new Map<string, AnyTestCase[]>();
  for (const tc of cases) {
    const key = tc.module || tc.feature || 'General';
    (groups.get(key) || groups.set(key, []).get(key)!).push(tc);
  }

  const lines: string[] = [];
  lines.push('# Test Cases');
  lines.push('');
  lines.push(`Generated by JBS IntelliQE — ${cases.length} test case(s).`);
  lines.push('');
  lines.push('| Module | Cases |');
  lines.push('|---|---|');
  for (const [mod, list] of groups) lines.push(`| ${mod} | ${list.length} |`);
  lines.push('');

  for (const [mod, list] of groups) {
    lines.push(`## ${mod}`);
    lines.push('');
    for (const tc of list) {
      lines.push(`### ${tc.id ? `${tc.id} — ` : ''}${titleOf(tc)}`);
      const meta = [
        tc.feature ? `**Feature:** ${tc.feature}` : '',
        tc.priority ? `**Priority:** ${tc.priority}` : '',
        tc.type ? `**Type:** ${tc.type}` : '',
        tc.severity ? `**Severity:** ${tc.severity}` : '',
      ].filter(Boolean).join(' · ');
      if (meta) lines.push(meta);
      if (tc.description) { lines.push(''); lines.push(tc.description); }
      if (tc.precondition) { lines.push(''); lines.push(`**Precondition:** ${tc.precondition}`); }
      const steps = stepsBlock(tc, '\n');
      if (steps) {
        lines.push('');
        lines.push('**Steps:**');
        lines.push('');
        lines.push(steps);
      }
      const expected = expectedOf(tc);
      if (expected) { lines.push(''); lines.push(`**Expected Result:** ${expected}`); }
      if (tc.tags && tc.tags.length) { lines.push(''); lines.push(`**Tags:** ${tc.tags.join(', ')}`); }
      lines.push('');
    }
  }
  return lines.join('\n');
}

/** Build an Excel/Jira/TestRail-friendly CSV (BOM for Excel). */
function buildCsv(cases: AnyTestCase[]): string {
  const header = 'TC ID,Title,Module,Feature,Priority,Type,Precondition,Steps,Expected Result,Status';
  const rows = cases.map((tc) =>
    [
      tc.id, titleOf(tc), tc.module || '', tc.feature || '', tc.priority || '', tc.type || '',
      tc.precondition || '', stepsBlock(tc, ' | '), expectedOf(tc), tc.status || '',
    ].map(csvEscape).join(','),
  );
  return '﻿' + header + '\n' + rows.join('\n');
}

/**
 * Render the test cases as deliverable documents (Markdown + CSV) under `docs/`.
 * Returns [] when there are no test cases.
 */
export function buildTestCaseDocs(cases: AnyTestCase[] | undefined): GitFile[] {
  if (!Array.isArray(cases) || cases.length === 0) return [];
  return [
    { path: 'docs/TEST-CASES.md', content: buildMarkdown(cases) },
    { path: 'docs/test-cases.csv', content: buildCsv(cases) },
  ];
}
