import { useState, useEffect, useCallback, useRef } from 'react';
import { Loader2, FileText, FileCode2, RefreshCw, ChevronDown, Download, BarChart3, PieChart, Plug } from 'lucide-react';
import {
  getReportsSummary,
  generateAllureReport, getAllureReportStatus,
  generateHtmlReport, getHtmlReportStatus,
} from '@/services/api';
import ErrorAlert from '@/components/feedback/ErrorAlert';
import { normalizeError, type NormalizedError } from '@/utils/apiError';
import CoverageDashboard from '@/components/reports/CoverageDashboard';
import TestRailDashboard from '@/components/reports/TestRailDashboard';

type ReportTab = 'coverage' | 'testrail' | 'reports';
type ReportFormat = 'allure' | 'html';

interface ReportData {
  recentRuns: {
    id: string;
    storyKey: string | null;
    storyTitle: string | null;
    source: string | null;
    createdAt: string;
    caseCount: number;
  }[];
}

interface ReportStatus {
  exists: boolean;
  generatedAt?: string;
  reportUrl?: string;
}

const FORMATS: { id: ReportFormat; label: string; icon: typeof FileText }[] = [
  { id: 'allure', label: 'Allure', icon: FileText },
  { id: 'html', label: 'HTML Report', icon: FileCode2 },
];

export default function ReportsPage() {
  const [tab, setTab] = useState<ReportTab>('coverage');
  const [data, setData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Which report format the "Test Reports" tab is generating / showing.
  const [format, setFormat] = useState<ReportFormat>('allure');
  const [reportStatus, setReportStatus] = useState<ReportStatus | null>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [reportError, setReportError] = useState<NormalizedError | null>(null);
  const [selectedRunId, setSelectedRunId] = useState<string>('');
  const [showRunDropdown, setShowRunDropdown] = useState(false);
  // Keyed by `${format}:${runId}` so each format auto-generates at most once.
  const autoGeneratedRef = useRef<Set<string>>(new Set());

  useEffect(() => {
    (async () => {
      try {
        const result = await getReportsSummary();
        setData(result);
        if (result?.recentRuns?.length > 0) {
          setSelectedRunId(result.recentRuns[0].id);
        }
      } catch (err) {
        setError(normalizeError(err).message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const checkStatus = useCallback(async (fmt: ReportFormat, runId?: string) => {
    setReportLoading(true);
    try {
      const statusFn = fmt === 'html' ? getHtmlReportStatus : getAllureReportStatus;
      const status = await statusFn(runId || undefined);
      setReportStatus(status);
      setReportError(null);
    } catch {
      setReportStatus(null);
    } finally {
      setReportLoading(false);
    }
  }, []);

  useEffect(() => {
    checkStatus(format, selectedRunId || undefined);
  }, [checkStatus, format, selectedRunId]);

  const handleGenerate = useCallback(async (runIdOverride?: string) => {
    const runId = runIdOverride ?? selectedRunId;
    if (!runId) {
      setReportError(normalizeError({
        isAxiosError: true,
        response: { status: 400, data: { code: 'NO_RUN', error: 'Select a run to generate a report for.', hint: 'Pick a run from the dropdown above.' } },
      }));
      return;
    }
    setGenerating(true);
    setReportError(null);
    try {
      const genFn = format === 'html' ? generateHtmlReport : generateAllureReport;
      const result = await genFn(runId);
      setReportStatus({ exists: true, generatedAt: result.generatedAt, reportUrl: result.reportUrl });
    } catch (err) {
      setReportError(normalizeError(err));
    } finally {
      setGenerating(false);
    }
  }, [selectedRunId, format]);

  // Auto-generate on first view of a (format, run) pair if none exists yet.
  // Only when the Test Reports tab is active — viewing Coverage shouldn't run anything.
  useEffect(() => {
    if (tab !== 'reports') return;
    if (!selectedRunId) return;
    if (reportLoading || generating) return;
    if (!reportStatus) return;
    if (reportStatus.exists) return;
    const key = `${format}:${selectedRunId}`;
    if (autoGeneratedRef.current.has(key)) return;
    autoGeneratedRef.current.add(key);
    handleGenerate(selectedRunId);
  }, [tab, format, selectedRunId, reportStatus, reportLoading, generating, handleGenerate]);

  const selectedRunLabel = selectedRunId
    ? data?.recentRuns.find(r => r.id === selectedRunId)?.storyKey || selectedRunId.slice(0, 8)
    : 'Select a run';

  const downloadUrl = reportStatus?.reportUrl?.replace(/\/index\.html$/, '/download');
  const formatLabel = format === 'html' ? 'HTML' : 'Allure';

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#3366FF] to-[#2645D6] flex items-center justify-center shadow-md shadow-violet-500/25">
          <BarChart3 className="w-5 h-5 text-white" />
        </div>
        <div>
          <h1 className="text-lg font-semibold text-[#1E3A8A]">Reports</h1>
          <p className="text-sm text-[#6B7280]">Test-case coverage &amp; Allure / HTML execution reports</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-1 border-b border-[#DCE7FF] overflow-x-auto">
        {([
          ['coverage', 'Coverage', PieChart],
          ['testrail', 'TestRail', Plug],
          ['reports', 'Test Reports', FileText],
        ] as const).map(([id, label, Icon]) => (
          <button
            key={id}
            onClick={() => setTab(id as ReportTab)}
            className={`flex items-center gap-2 px-4 py-2.5 text-sm font-medium -mb-px border-b-2 transition-colors whitespace-nowrap ${
              tab === id ? 'border-[#3366FF] text-[#3366FF]' : 'border-transparent text-[#6B7280] hover:text-[#1E3A8A]'
            }`}
          >
            <Icon className="w-4 h-4" /> {label}
          </button>
        ))}
      </div>

      {tab === 'coverage' && <CoverageDashboard />}

      {tab === 'testrail' && <TestRailDashboard />}

      {tab === 'reports' && (loading ? (
        <div className="flex items-center justify-center h-64">
          <Loader2 className="w-8 h-8 text-[#2143A8] animate-spin" />
          <span className="ml-3 text-sm text-[#6B7280]">Loading reports...</span>
        </div>
      ) : error ? (
        <div className="max-w-2xl mx-auto py-10">
          <ErrorAlert
            error={{ code: 'LOAD_FAIL', title: 'Could not load reports', message: error, severity: 'error', retryable: true }}
            onRetry={() => window.location.reload()}
          />
        </div>
      ) : (
      <div className="space-y-4">
        {/* Controls Bar */}
        <div className="relative z-50 bg-white/80 backdrop-blur-sm rounded-2xl border border-[#DCE7FF] shadow-sm p-4">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
            {/* Format toggle — pick which report to generate/view */}
            <div className="flex items-center gap-1 p-1 bg-[#EEF4FF] border border-[#C5D6FF] rounded-lg">
              {FORMATS.map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setFormat(id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
                    format === id ? 'bg-white text-[#3366FF] shadow-sm' : 'text-[#6B7280] hover:text-[#1E3A8A]'
                  }`}
                >
                  <Icon className="w-4 h-4" /> {label}
                </button>
              ))}
            </div>

            {/* Run Selector */}
            <div className="relative">
              <button
                onClick={() => setShowRunDropdown(!showRunDropdown)}
                className="flex items-center gap-2 px-3 py-2 text-sm bg-[#EEF4FF] border border-[#C5D6FF] rounded-lg hover:bg-[#DCE7FF] transition-colors min-w-[200px]"
              >
                <FileText className="w-4 h-4 text-[#2143A8]" />
                <span className="text-[#1E3A8A] truncate flex-1 text-left">{selectedRunLabel}</span>
                <ChevronDown className="w-4 h-4 text-[#6B7280]" />
              </button>
              {showRunDropdown && (
                <div className="absolute top-full left-0 mt-1 w-72 bg-white rounded-xl border border-[#DCE7FF] shadow-xl shadow-violet-500/10 z-[100] max-h-64 overflow-y-auto">
                  {data?.recentRuns?.map((run) => (
                    <button
                      key={run.id}
                      onClick={() => { setSelectedRunId(run.id); setShowRunDropdown(false); }}
                      className={`w-full text-left px-3 py-2 text-sm hover:bg-[#EEF4FF] transition-colors border-t border-[#EEF4FF] ${
                        selectedRunId === run.id ? 'bg-[#DCE7FF] text-[#2143A8] font-medium' : 'text-[#1E3A8A]'
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        {run.storyKey && (
                          <span className="px-1.5 py-0.5 bg-[#DCE7FF] text-[#2143A8] rounded text-xs font-mono">{run.storyKey}</span>
                        )}
                        <span className="truncate">{run.storyTitle || 'Manual Input'}</span>
                      </div>
                      <div className="text-xs text-[#6B7280] mt-0.5">
                        {run.caseCount} cases &middot; {new Date(run.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            <button
              onClick={() => handleGenerate()}
              disabled={generating}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-violet-200"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              {generating ? (format === 'html' ? 'Building…' : 'Running tests…') : `Generate ${formatLabel} Report`}
            </button>

            {reportStatus?.exists && downloadUrl && (
              <a
                href={downloadUrl}
                download
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[#2143A8] bg-white border border-[#C5D6FF] rounded-lg hover:bg-[#EEF4FF] transition-all shadow-sm"
              >
                <Download className="w-4 h-4" />
                Download
              </a>
            )}

            {reportStatus?.generatedAt && (
              <span className="text-xs text-[#6B7280] ml-auto">
                Last generated: {new Date(reportStatus.generatedAt).toLocaleString('en-US', {
                  month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
                })}
              </span>
            )}
          </div>

          {reportError && (
            <div className="mt-3">
              <ErrorAlert
                error={reportError}
                onDismiss={() => setReportError(null)}
                onRetry={() => handleGenerate()}
              />
            </div>
          )}
        </div>

        {reportLoading ? (
          <div className="flex items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-2xl border border-[#DCE7FF] shadow-sm">
            <Loader2 className="w-8 h-8 text-[#2143A8] animate-spin" />
            <span className="ml-3 text-sm text-[#6B7280]">Checking report status...</span>
          </div>
        ) : reportStatus?.exists && reportStatus.reportUrl ? (
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl border border-[#DCE7FF] shadow-sm overflow-hidden">
            <iframe
              key={reportStatus.reportUrl + reportStatus.generatedAt}
              src={reportStatus.reportUrl}
              className="w-full border-0"
              style={{ height: 'calc(100vh - 220px)', minHeight: '500px' }}
              title={`${formatLabel} Test Report`}
            />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-2xl border border-[#DCE7FF] shadow-sm">
            <FileText className="w-14 h-14 text-[#6B7280] mb-4" />
            <h3 className="text-lg font-semibold text-[#1E3A8A] mb-2">
              {generating ? `Building ${formatLabel} report…` : `No ${formatLabel} Report Generated`}
            </h3>
            <p className="text-sm text-[#6B7280] max-w-md text-center mb-4">
              {generating
                ? (format === 'html'
                    ? 'Building a branded HTML summary from this run’s execution results.'
                    : 'Executing Playwright against the automation scripts for this run. This can take a moment.')
                : (format === 'html'
                    ? 'Click "Generate HTML Report" to build a branded, self-contained HTML summary of this run.'
                    : 'Click "Generate Allure Report" to run the stored Playwright scripts and build a real Allure report.')}
            </p>
            <button
              onClick={() => handleGenerate()}
              disabled={generating}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-white bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 rounded-lg disabled:opacity-50 transition-all shadow-md shadow-violet-200"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              {generating ? 'Generating...' : `Generate ${formatLabel} Report`}
            </button>
          </div>
        )}
      </div>
      ))}
    </div>
  );
}
