import { useState, useEffect, useCallback, useRef } from 'react';
import { Loader2, FileText, RefreshCw, BarChart3 } from 'lucide-react';
import { getReportsSummary, generateAllureReport, getAllureReportStatus, getLatestAllureReport } from '@/services/api';
import ErrorAlert from '@/components/feedback/ErrorAlert';
import { useToast } from '@/components/feedback/ToastProvider';
import { normalizeError } from '@/utils/apiError';

interface ReportStatus {
  exists: boolean;
  generatedAt?: string;
  /** Playwright HTML report at the run root — shown under "Basic Report". */
  reportUrl?: string;
  /** Allure report in the run's /allure subfolder — shown under "Allure Report". */
  allureReportUrl?: string;
}

type ReportTab = 'basic' | 'allure';

export default function ReportsPage() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [status, setStatus] = useState<ReportStatus | null>(null);
  const [statusLoading, setStatusLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const toast = useToast();
  // The latest run is resolved on load and never shown as a picker — the page
  // always reflects the most recent execution.
  const [runId, setRunId] = useState<string>('');
  const autoGeneratedRef = useRef<Set<string>>(new Set());

  const [tab, setTab] = useState<ReportTab>('basic');

  // On load, resolve the most-recently-generated report (the latest execution).
  useEffect(() => {
    (async () => {
      try {
        let latest: { exists: boolean; runId?: string } | null = null;
        try { latest = await getLatestAllureReport(); } catch { /* fall back below */ }

        if (latest?.exists && latest.runId) {
          setRunId(latest.runId);
        } else {
          try {
            const result = await getReportsSummary();
            const runs = result?.recentRuns ?? [];
            if (runs.length > 0) setRunId(runs[0].id);
          } catch { /* leave unset */ }
        }
      } catch (err) {
        setError(normalizeError(err).message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const checkStatus = useCallback(async (id?: string) => {
    setStatusLoading(true);
    try {
      const s = await getAllureReportStatus(id || undefined);
      setStatus(s as ReportStatus);
    } catch {
      setStatus(null);
    } finally {
      setStatusLoading(false);
    }
  }, []);

  useEffect(() => {
    checkStatus(runId || undefined);
  }, [checkStatus, runId]);

  // `silent` suppresses the toast — used by the auto-generate-on-load path, where
  // the "No Report Yet" empty state already explains it; only an explicit click toasts.
  const handleGenerate = useCallback(async (idOverride?: string, opts?: { silent?: boolean }) => {
    const id = idOverride ?? runId;
    if (!id) {
      if (!opts?.silent) toast.error('No test run found', 'Run a test execution from the Chat flow first.');
      return;
    }
    setGenerating(true);
    try {
      await generateAllureReport(id);
      // Re-read status so we pick up BOTH the basic + allure URLs.
      await checkStatus(id);
    } catch (err) {
      if (!opts?.silent) {
        const n = normalizeError(err);
        const noRun = /no automation scripts|no execution|no run|NO_SCRIPTS|NO_RUN/i.test(`${n.code || ''} ${n.message || ''}`);
        toast.error(
          'Report unavailable',
          noRun
            ? 'Run a test execution from the Chat flow first, then try again.'
            : 'Could not generate the report. Please try again.',
        );
      }
    } finally {
      setGenerating(false);
    }
  }, [runId, checkStatus, toast]);

  // Auto-generate on first view if no report exists yet for the latest run.
  useEffect(() => {
    if (!runId) return;
    if (statusLoading || generating) return;
    if (!status) return;
    if (status.exists) return;
    if (autoGeneratedRef.current.has(runId)) return;
    autoGeneratedRef.current.add(runId);
    handleGenerate(runId, { silent: true });
  }, [runId, status, statusLoading, generating, handleGenerate]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 text-[#7C3AED] animate-spin" />
        <span className="ml-3 text-sm text-[#6B7280]">Loading reports...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-2xl mx-auto py-10">
        <ErrorAlert
          error={{ code: 'LOAD_FAIL', title: 'Could not load reports', message: error, severity: 'error', retryable: true }}
          onRetry={() => window.location.reload()}
        />
      </div>
    );
  }

  const basicReady = !!(status?.exists && status.reportUrl);
  const allureReady = !!(status?.exists && status.allureReportUrl);
  const activeUrl = tab === 'basic' ? status?.reportUrl : status?.allureReportUrl;
  const activeReady = tab === 'basic' ? basicReady : allureReady;

  const tabBtn = (id: ReportTab, label: string, Icon: React.ElementType) => (
    <button
      onClick={() => setTab(id)}
      className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors ${
        tab === id ? 'bg-[#7C3AED] text-white shadow-md shadow-purple-200' : 'text-[#6B7280] hover:bg-[#F5F3FF]'
      }`}
    >
      <Icon className="w-4 h-4" /> {label}
    </button>
  );

  return (
    <div className="space-y-4">
      {/* Controls Bar: tabs + generate */}
      <div className="bg-white/80 backdrop-blur-sm rounded-xl border border-[#DDD6FE]/60 p-3 flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-1 bg-[#F5F3FF]/60 rounded-xl p-1">
          {tabBtn('basic', 'Basic Report', BarChart3)}
          {tabBtn('allure', 'Allure Report', FileText)}
        </div>

        <button
          onClick={() => handleGenerate()}
          disabled={generating}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#7C3AED] rounded-lg hover:bg-[#6D28D9] disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-purple-200"
        >
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
          {generating ? 'Running tests…' : 'Generate Report'}
        </button>

        {status?.generatedAt && (
          <span className="text-xs text-[#A5B4FC] ml-auto">
            Latest report · {new Date(status.generatedAt).toLocaleString('en-US', {
              month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
            })}
          </span>
        )}
      </div>

      {/* Body */}
      {statusLoading ? (
        <div className="flex items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-xl border border-[#DDD6FE]/60">
          <Loader2 className="w-8 h-8 text-[#7C3AED] animate-spin" />
          <span className="ml-3 text-sm text-[#6B7280]">Checking report status...</span>
        </div>
      ) : activeReady && activeUrl ? (
        <div className="bg-white/80 backdrop-blur-sm rounded-xl border border-[#DDD6FE]/60 overflow-hidden">
          <iframe
            key={activeUrl + (status?.generatedAt || '')}
            src={activeUrl}
            className="w-full border-0"
            style={{ height: 'calc(100vh - 200px)', minHeight: '500px' }}
            title={tab === 'basic' ? 'Playwright HTML Report' : 'Allure Test Report'}
          />
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-xl border border-[#DDD6FE]/60">
          <FileText className="w-14 h-14 text-[#A5B4FC] mb-4" />
          <h3 className="text-lg font-semibold text-[#1E1B4B] mb-2">
            {generating
              ? 'Running tests and building the report…'
              : basicReady && tab === 'allure'
                ? 'No Allure Report for this run'
                : 'No Report Yet'}
          </h3>
          <p className="text-sm text-[#6B7280] max-w-md text-center mb-4">
            {generating
              ? 'Executing Playwright against the latest run. This can take a moment.'
              : basicReady && tab === 'allure'
                ? 'This run has a Basic (Playwright) report but no Allure report was produced. Switch to Basic Report, or re-run the execution.'
                : 'Run a test execution from the Chat flow, or click "Generate Report" to build one for the latest run.'}
          </p>
          {basicReady && tab === 'allure' ? (
            <button
              onClick={() => setTab('basic')}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-[#7C3AED] border border-[#DDD6FE] rounded-lg hover:bg-[#F5F3FF] transition-all"
            >
              <BarChart3 className="w-4 h-4" /> View Basic Report
            </button>
          ) : (
            <button
              onClick={() => handleGenerate()}
              disabled={generating}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-white bg-[#7C3AED] rounded-lg hover:bg-[#6D28D9] disabled:opacity-50 transition-all shadow-md shadow-purple-200"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              {generating ? 'Generating...' : 'Generate Report'}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
