import { useState, useEffect, useCallback, useRef } from 'react';
import { Loader2, FileText, RefreshCw, ChevronDown, Download } from 'lucide-react';
import { getReportsSummary, generateAllureReport, getAllureReportStatus } from '@/services/api';
import ErrorAlert from '@/components/feedback/ErrorAlert';
import { normalizeError, type NormalizedError } from '@/utils/apiError';

interface ReportData {
  recentRuns: {
    id: string;
    storyKey: string | null;
    storyTitle: string | null;
    source: string | null;
    createdAt: string;
    caseCount: number;
  }[];
}

interface AllureStatus {
  exists: boolean;
  generatedAt?: string;
  reportUrl?: string;
}

export default function ReportsPage() {
  const [data, setData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [allureStatus, setAllureStatus] = useState<AllureStatus | null>(null);
  // The run id that `allureStatus` was fetched for. On rapid run switches the
  // status fetch is async, so this lets the auto-generate effect confirm the
  // status in state actually belongs to the currently selected run before
  // acting on it (otherwise it could auto-generate off a stale status).
  const [statusRunId, setStatusRunId] = useState<string>('');
  const [allureLoading, setAllureLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [allureError, setAllureError] = useState<NormalizedError | null>(null);
  const [selectedRunId, setSelectedRunId] = useState<string>('');
  const [showRunDropdown, setShowRunDropdown] = useState(false);
  const autoGeneratedRef = useRef<Set<string>>(new Set());

  useEffect(() => {
    (async () => {
      try {
        const result = await getReportsSummary();
        setData(result);
        if (result?.recentRuns?.length > 0) {
          setSelectedRunId(result.recentRuns[0].id);
        }
      } catch (err) {
        setError(normalizeError(err).message);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const checkAllureStatus = useCallback(async (runId?: string) => {
    setAllureLoading(true);
    // Invalidate any prior status while we fetch this run's, so a stale status
    // can never satisfy the auto-generate guard mid-switch.
    setStatusRunId('');
    try {
      const status = await getAllureReportStatus(runId || undefined);
      setAllureStatus(status);
      setStatusRunId(runId || '');
      setAllureError(null);
    } catch {
      setAllureStatus(null);
      setStatusRunId('');
    } finally {
      setAllureLoading(false);
    }
  }, []);

  useEffect(() => {
    checkAllureStatus(selectedRunId || undefined);
  }, [checkAllureStatus, selectedRunId]);

  const handleGenerate = useCallback(async (runIdOverride?: string) => {
    const runId = runIdOverride ?? selectedRunId;
    if (!runId) {
      setAllureError(normalizeError({
        isAxiosError: true,
        response: { status: 400, data: { code: 'NO_RUN', error: 'Select a run to generate a report for.', hint: 'Pick a run from the dropdown above.' } },
      }));
      return;
    }
    setGenerating(true);
    setAllureError(null);
    try {
      const result = await generateAllureReport(runId);
      setAllureStatus({
        exists: true,
        generatedAt: result.generatedAt,
        reportUrl: result.reportUrl,
      });
    } catch (err) {
      setAllureError(normalizeError(err));
    } finally {
      setGenerating(false);
    }
  }, [selectedRunId]);

  // Auto-generate on first view of a run if no report exists yet.
  useEffect(() => {
    if (!selectedRunId) return;
    if (allureLoading || generating) return;
    if (!allureStatus) return;
    // Only act when the status in state was fetched for THIS run — otherwise a
    // rapid run switch could trigger generation off the previous run's status.
    if (statusRunId !== selectedRunId) return;
    if (allureStatus.exists) return;
    if (autoGeneratedRef.current.has(selectedRunId)) return;
    autoGeneratedRef.current.add(selectedRunId);
    handleGenerate(selectedRunId);
  }, [selectedRunId, statusRunId, allureStatus, allureLoading, generating, handleGenerate]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 text-[#155dfc] animate-spin" />
        <span className="ml-3 text-sm text-[#6B7280]">Loading reports...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-2xl mx-auto py-10">
        <ErrorAlert
          error={{ code: 'LOAD_FAIL', title: 'Could not load reports', message: error, severity: 'error', retryable: true }}
          onRetry={() => window.location.reload()}
        />
      </div>
    );
  }

  const selectedRunLabel = selectedRunId
    ? data?.recentRuns.find(r => r.id === selectedRunId)?.storyKey || selectedRunId.slice(0, 8)
    : 'Select a run';

  return (
    <div className="space-y-6">
      <div className="space-y-4">
        {/* Controls Bar */}
        <div className="relative z-50 bg-white/80 backdrop-blur-sm rounded-xl border border-[#C9DCFF]/60 p-4">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
            {/* Run Selector */}
            <div className="relative">
              <button
                onClick={() => setShowRunDropdown(!showRunDropdown)}
                className="flex items-center gap-2 px-3 py-2 text-sm bg-[#EFF5FF] border border-[#C9DCFF] rounded-lg hover:bg-[#DEEAFF] transition-colors min-w-[200px]"
              >
                <FileText className="w-4 h-4 text-[#155dfc]" />
                <span className="text-[#1E1B4B] truncate flex-1 text-left">{selectedRunLabel}</span>
                <ChevronDown className="w-4 h-4 text-[#93B4FB]" />
              </button>
              {showRunDropdown && (
                <div className="absolute top-full left-0 mt-1 w-72 bg-white rounded-xl border border-[#C9DCFF] shadow-xl shadow-blue-200/60 z-[100] max-h-64 overflow-y-auto">
                  {data?.recentRuns?.map((run) => (
                    <button
                      key={run.id}
                      onClick={() => { setSelectedRunId(run.id); setShowRunDropdown(false); }}
                      className={`w-full text-left px-3 py-2 text-sm hover:bg-[#EFF5FF] transition-colors border-t border-[#EFF5FF] ${
                        selectedRunId === run.id ? 'bg-[#DEEAFF] text-[#155dfc] font-medium' : 'text-[#1E1B4B]'
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        {run.storyKey && (
                          <span className="px-1.5 py-0.5 bg-[#DEEAFF] text-[#155dfc] rounded text-xs font-mono">{run.storyKey}</span>
                        )}
                        <span className="truncate">{run.storyTitle || 'Manual Input'}</span>
                      </div>
                      <div className="text-xs text-[#93B4FB] mt-0.5">
                        {run.caseCount} cases &middot; {new Date(run.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            <button
              onClick={() => handleGenerate()}
              disabled={generating}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#155dfc] rounded-lg hover:bg-[#124fd6] disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-blue-200"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              {generating ? 'Running tests…' : 'Generate Report'}
            </button>

            {allureStatus?.exists && allureStatus.reportUrl && (
              <a
                href={allureStatus.reportUrl.replace(/\/index\.html$/, '/download')}
                download
                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[#155dfc] bg-white border border-[#C9DCFF] rounded-lg hover:bg-[#EFF5FF] transition-all shadow-sm"
              >
                <Download className="w-4 h-4" />
                Download
              </a>
            )}

            {allureStatus?.generatedAt && (
              <span className="text-xs text-[#93B4FB] ml-auto">
                Last generated: {new Date(allureStatus.generatedAt).toLocaleString('en-US', {
                  month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
                })}
              </span>
            )}
          </div>

          {allureError && (
            <div className="mt-3">
              <ErrorAlert
                error={allureError}
                onDismiss={() => setAllureError(null)}
                onRetry={() => handleGenerate()}
              />
            </div>
          )}
        </div>

        {allureLoading ? (
          <div className="flex items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-xl border border-[#C9DCFF]/60">
            <Loader2 className="w-8 h-8 text-[#155dfc] animate-spin" />
            <span className="ml-3 text-sm text-[#6B7280]">Checking report status...</span>
          </div>
        ) : allureStatus?.exists && allureStatus.reportUrl ? (
          <div className="bg-white/80 backdrop-blur-sm rounded-xl border border-[#C9DCFF]/60 overflow-hidden">
            <iframe
              key={allureStatus.reportUrl + allureStatus.generatedAt}
              src={allureStatus.reportUrl}
              className="w-full border-0"
              style={{ height: 'calc(100vh - 220px)', minHeight: '500px' }}
              title="Allure Test Report"
            />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-96 bg-white/80 backdrop-blur-sm rounded-xl border border-[#C9DCFF]/60">
            <FileText className="w-14 h-14 text-[#93B4FB] mb-4" />
            <h3 className="text-lg font-semibold text-[#1E1B4B] mb-2">
              {generating ? 'Running tests and building Allure report…' : 'No Allure Report Generated'}
            </h3>
            <p className="text-sm text-[#6B7280] max-w-md text-center mb-4">
              {generating
                ? 'Executing Playwright against the automation scripts for this run. This can take a moment.'
                : 'Click "Generate Report" to run the stored Playwright scripts and build a real Allure report.'}
            </p>
            <button
              onClick={() => handleGenerate()}
              disabled={generating}
              className="flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-white bg-[#155dfc] rounded-lg hover:bg-[#124fd6] disabled:opacity-50 transition-all shadow-md shadow-blue-200"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              {generating ? 'Generating...' : 'Generate Report'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
